% This script is written and read by pdetool and should NOT be edited.
% There are two recommended alternatives:
 % 1) Export the required variables from pdetool and create a MATLAB script
 %    to perform operations on these.
 % 2) Define the problem completely using a MATLAB script. See
 %    http://www.mathworks.com/help/pde/examples/index.html for examples
 %    of this approach.
function pdemodel
[pde_fig,ax]=pdeinit;
pdetool('appl_cb',1);
set(ax,'DataAspectRatio',[1 0.021428571428571432 1]);
set(ax,'PlotBoxAspectRatio',[70 46.666666666666657 20]);
set(ax,'XLim',[0 7]);
set(ax,'YLim',[0 0.10000000000000001]);
set(ax,'XTickMode','auto');
set(ax,'YTickMode','auto');

% Geometry description:
pderect([0 5 0.050000000000000003 0],'R1');
set(findobj(get(pde_fig,'Children'),'Tag','PDEEval'),'String','R1')

% Boundary conditions:
pdetool('changemode',0)
pdesetbd(4,...
'dir',...
1,...
'1',...
'0')
pdesetbd(3,...
'dir',...
1,...
'1',...
'0')
pdesetbd(2,...
'dir',...
1,...
'1',...
'0')
pdesetbd(1,...
'dir',...
1,...
'1',...
'0')

% Mesh generation:
setappdata(pde_fig,'trisize',0.050000000000000003);
setappdata(pde_fig,'Hgrad',1.1000000000000001);
setappdata(pde_fig,'refinemethod','regular');
setappdata(pde_fig,'jiggle',char('off','mean',''));
setappdata(pde_fig,'MesherVersion','preR2013a');
pdetool('initmesh')
pdetool('refine')

% PDE coefficients:
pdeseteq(1,...
'1',...
'0.0',...
'10',...
'1.0',...
'0:10',...
'0.0',...
'0.0',...
'[0 100]')
setappdata(pde_fig,'currparam',...
['1  ';...
'0.0';...
'10 ';...
'1.0'])

% Solve parameters:
setappdata(pde_fig,'solveparam',...
char('0','2400','10','pdeadworst',...
'0.5','longest','0','1E-4','','fixed','Inf'))

% Plotflags and user data strings:
setappdata(pde_fig,'plotflags',[4 1 1 1 1 1 7 1 0 0 0 1 1 1 0 0 0 1]);
setappdata(pde_fig,'colstring','grad(u)');
setappdata(pde_fig,'arrowstring','');
setappdata(pde_fig,'deformstring','');
setappdata(pde_fig,'heightstring','');

% Solve PDE:
pdetool('solve')
%% CODE SNIPPET FOR POSTPROCESSING AND PLOTTING. UNCOMMENT, COPY AND PASTE SEPARATELY IN Matlab WINDOW TO USE. 
% p, e, t, u data must be first exported into the workspace
%% Velocity profile is plotted
% pdeplot(p,e,t,'xydata',u,'zdata',u,'contour','off','colormap','jet')
